Development
300ms/Design-Teardown pull request #1
Opened 2019-09-11 20:48 UTC by 300ms

Project 5 on Microverse: Design Teardrop

2019-09-11 21:08 UTC, samgaco commented
Reviewing

2019-09-11 21:16 UTC, samgaco requested changes
#### Hi  @300ms and @Luzaks :high_brightness: 

#### Things to address before the approval:

1. The footer should contain centered links. 
2. Address errors given to you by the[ css validator.](https://jigsaw.w3.org)
3. The nav bar should contain `<div>` tags

------------------

* **[OPTIONAL]** Add some text to the body of the articles (there is only titles so far)

------------------


### Have into account :arrow_down: 

* Friendly reminder: You should use [Github flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) in this project. However, changing it now would take too much time. Please make sure you use [Github Flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) in the next project. 

* **[For your next code review requests]**  Use meaningful names for your Pull Requests
* **[For your next code review requests]**  Add a short summary of changes in Pull Request description

--------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-09-11 21:16 UTC, samgaco commented on index.html
> +            <h1>The standard Lorem Ipsum passage</h1>
The footer should contain centered links

2019-09-11 21:16 UTC, samgaco commented on index.html
> +
The nav bar should contain `<div>` containers

2019-09-12 00:32 UTC, Ispirett approved these changes
Hey, @Luzaks @300ms Great Job with Changes.
![image](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png). 

**You can merge this project now!!!** 

**[Optional] for the following**
- [ ] You can add a block that represents an image  for the section under the section with the following text 
`Contrary to popular belief, Lorem Ipsum is not simply random text. It has`
- [ ] The footer you can give the  `a` links color that represents the contrast of that section like white

Github flow reminder.
Friendly reminder: You should use Github Flow in this project. However, changing it now would take too much time.
Please make sure you use Github/Git Flow in the next project. You will find instructions in the Patwright lesson description.

2019-09-12 19:33 UTC, merged